global:
  resolve_timeout: 5m

route:
  receiver: 'discord'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h

receivers:
  - name: 'discord'
    webhook_configs:
      - url: 'https://discord.com/api/webhooks/1397507242886168607/SlEa0_AHrau_kxtNZ5N8HUCc4SbxrP3z2AfbKW3zGt7U8-sL_zJbaVTe95_aTM1rnQvC'
        send_resolved: true
