---
global:
  resolve_timeout: 5m

route:
  receiver: discord-webhook
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h

receivers:
  - name: discord-webhook
    webhook_configs:
      - url: ${DISCORD_WEBHOOK_URL}
        send_resolved: true
